# `marks' is a text format + converter.  It can be found at
# `http://github.com/bsummer4/marks'.  For now, the formatting depends
# on plan9port.
#
# :TODO: Poor formatting of the resulting PDFs
# 	The formatting isn't polished at all, so don't bother installing
# 	plan9port for this.

src = tut wp ref
out = ${src:%=%.pdf}
all:V: $out
clean:V:
	rm -f $out

%.pdf: % mkfile hdr.tr
	( (cat hdr.tr; marks) | 9 troff -ms | 9 tr2post | 9 psfonts | ps2pdf - -
   ) <$stem >$stem.pdf
