# The order of files in $src matters.  Source files files earlier in the
# list may not depend on things defined in files later in the list.

module = tiger
cm = @/smlnj-lib.cm @/basis.cm @/ml-yacc-lib.cm
mlb =\
 @/basis/basis.mlb @/smlnj-lib/Util/smlnj-lib.mlb\
 @/mlyacc-lib/mlyacc-lib.mlb

src =\
 util.E.sml sym.E.sml sexp.E.sml ast.E.sml ir.E.sml cir.E.sml sa.E.sml\
 ll.E.sml toc.E.sml parseutils.E.sml tiger.E.grm.sig tiger.E.grm.sml\
 tiger.E.lex.sml

all:V: $src

<../ml.mk
<../m4.mk
